### PR TITLE
Some improvments

### PR DESCRIPTION
**Pull request by xIsm4**
Implemeting getLogger# to avoid warnings on high paper versions, also improved some things.

### CODE REVIEW

**Comment by xIsm4** [comment]
Also, renember ur plugin here or won't work: https://bstats.org/add-plugin

**Comment by RubenArtz** [comment]
Thanks for correcting some things, I didn't have time to check it.

**Comment by xIsm4** [comment]
Oh, if u want i can fix u some other things.

**Comment by RubenArtz** [comment]
Of course, I've had some problems with maven. 😢

**Comment by xIsm4** [comment]
> Of course, I've had some problems with maven. 😢

Well, actually i can switch it to gradle, but u shouldn't implement Literaly the "api" of bStats giving a heavy heigth btw, bugs using that logger on paper

**Comment by RubenArtz** [comment]
Okay thank you very much I will keep it in mind

**Review by RubenArtz — APPROVED** [review]

**Review by RubenArtz — APPROVED** [review]

**Pull request closed without merging**
